---
name: deploy with helm and traefik
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --snapshot --rm-dist --skip-publish
      - name: Setup kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          config: "ci/kind-config.yaml"
          version: "v0.11.1"
          image: kindest/node:v1.23.1
      - name: Show cluster info and switch to kube-system
        run: |
          kubectl cluster-info
          kubectl get nodes
          echo "current-context:" $(kubectl config current-context)
          kubectl config set-context --current --namespace kube-system
      - name: Deploy traefik
        timeout-minutes: 2
        run: |
          helm repo add traefik https://helm.traefik.io/traefik
          helm repo update
          helm install --namespace=kube-system  traefik traefik/traefik
      - name: Import image into kind
        run: |
          docker images
          docker tag postfinance/kubenurse:latest \
            postfinance/kubenurse:latest-ci
          kind load docker-image postfinance/kubenurse:latest-ci
      - name: Deploy example setup
        run: |
          helm upgrade kubenurse \
            --install helm/kubenurse/ \
            -f helm/kubenurse/values.yaml \
            --set ingress.url=ingress-nginx-controller.ingress-nginx.svc.cluster.local,daemonset.image.tag=latest-ci \
            --wait
      - name: Wait for pods
        timeout-minutes: 1
        run: |
          sleep 15 # wait for the scheduler to create pods
          kubectl -n kube-system wait pods -l app=kubenurse --for=condition=Ready
          kubectl -n kube-system get pods -l app=kubenurse
      - name: Check deployment
        uses: ./.github/actions/check-deployment
        with:
          namespace: kube-system
