---
name: lint and test
on:
  push:
  pull_request:
jobs:
  lint-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: golangci/golangci-lint-action@v2
      with:
        version: v1.46
        args: --timeout 5m
  lint-helm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Helm lint
      shell: bash
      run: |
        helm lint ./helm/kubenurse/
  test-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Run unit tests
      run: go test -race -covermode atomic -coverprofile=profile.cov ./...
    - name: Send coverage report
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        go install github.com/mattn/goveralls@v0.0.11
        goveralls -coverprofile=profile.cov -service=github
